### ISSUE TITLE
String updates

### ISSUE THREAD

**Issue by Alexejhero** [StopModReposts/StopModReposts.github.io#18]
## Home

> Reposting is _~~basically~~_ one of the worst things a mod author can go _~~through~~_ **through,** and here is why:

<details>
<summary>Complete string</summary>

> Reposting is one of the worst things a mod author can go through, and here is why:

</details>

> Developers live from income. If you download _~~on~~_ **from** reposting sites, they won't get any _~~revenue~~_ **revenue,** which _~~means~~_ **could mean** less mods **from them** in the future.

<details>
<summary>Complete string</summary>

> Developers live from income. If you download from reposting sites, they won't get any revenue, which could mean less mods from them in the future.

</details>

> _~~Mostly, reposting~~_ **Reposting** sites **might** link you to outdated versions, which _~~means~~_ **could mean** more _~~bugs and sometimes even game lags~~_ **bugs, crashes and errors** for you.

<details>
<summary>Complete string</summary>

> Reposting sites might link you to outdated versions, which could mean more bugs, crashes and errors for you.

</details>

> We do our _~~best,~~_ **best** to provide you with up-to date **site** lists, a browser extension to block _~~sites~~_ **sites,** and more.

<details>
<summary>Complete string</summary>

> We do our best to provide you with up-to date site lists, a browser extension to block sites, and more.

</details>

> Don't want to accidentally visit one? Download our browser extension to _~~stop the mod reposts!~~_ **be safe!**

<details>
<summary>Complete string</summary>

> Don't want to accidentally visit one? Download our browser extension to be safe!

</details>

> We submit **new** sites _~~nearly every month.~~_ **periodically.** Want to help other users? Find and upload sites so others won't download _~~on such sites.~~_ **from them.**

<details>
<summary>Complete string</summary>

> We submit new sites periodically. Want to help other users? Find and upload sites so others won't download from them.

</details>

> _~~Visit~~_ **You can visit** our **GitHub** repository to _~~find all new sites!~~_ **view the site lists.** Also, we're _~~allways~~_ **always** happy about a star!

<details>
<summary>Complete string</summary>

> You can visit our GitHub repository to view the site lists. Also, we're always happy about a star!

</details>

> We also have a _~~Subreddit:~~_ **subreddit:**

<details>
<summary>Complete string</summary>

> We also have a subreddit:

</details>

## About

> We're a team of developers that couldn't _~~see~~_ **stand** the reposting anymore. We know how frustrating it can _~~be, to see the own~~_ **be to see your own** work being stolen by others.

<details>
<summary>Complete string</summary>

> We're a team of developers that couldn't stand the reposting anymore. We know how frustrating it can be to see your own work being stolen by others.

</details>

## Get Involved

> We maintain a list of sites that illegally redistribute mods. _~~These sites mostly~~_ **Most of these sites** make ad revenue from every visit. _~~Visiting the reposting sites supports them.~~_ You can download our free extension for Chrome, Firefox and Opera _~~here.~~_ **here to flag any reposting sites.**

<details>
<summary>Complete string</summary>

> We maintain a list of sites that illegally redistribute mods. Most of these sites make ad revenue from every visit. You can download our free extension for Chrome, Firefox and Opera here to flag any reposting sites.

</details>

> If you discover a new _~~site,~~_ **site** and don't see it _~~on~~_ **in** our lists, _~~then feel free to~~_ **please** notify us about _~~the site~~_ **it** via the _~~Contact Form.~~_ **Contact Form or our Discord.**

<details>
<summary>Complete string</summary>

> If you discover a new site and don't see it in our lists, please notify us about it via the Contact Form or our Discord.

</details>

> Ask the mod authors if they _~~permitted~~_ **allowed** the reposting. _~~Please don't spam them, and only contact them, when multiple mods made by them where reposted.~~_

<details>
<summary>Complete string</summary>

> Ask the mod authors if they allowed the reposting.

</details>

> Every _~~Follower, Like and Retweet helps.~~_ **follower, like and retweet helps spread awareness amongst users who download mods.**  _~~Also, feel free to use~~_ **You can also use** our _~~Hashtag StopModReposts and #AntiModRepost.~~_ **hashtag: #StopModReposts.**

<details>
<summary>Complete string</summary>

> Every follower, like and retweet helps spread awareness amongst users who download mods. You can also use our hashtag: #StopModReposts.

</details>

> For _~~Mod Authors:~~_ **mod authors:** Request the removal of your mod.

<details>
<summary>Complete string</summary>

> For Mod Authors: mod authors: Request the removal of your mod.

</details>

## FAQ

> _~~Do you have an IRC Channel?~~_
> _~~Yes, #StopModReposts at irc.esper.net! Make sure to read the rules before joining.~~_
> **Do you have a Discord server?**
> **Yes, you can join our Discord server here.**

<details>
<summary>Complete string</summary>

> Do you have a Discord server?
> Yes, you can join our Discord server here.

</details>

> You can notify us about a site via _~~Social Media,~~_ the Contact Form on this _~~page or via~~_ **page,** the "Issues" tab on _~~GitHub.~~_ **GitHub, or in our Discord server.**

<details>
<summary>Complete string</summary>

> You can notify us about a site via the Contact Form on this page, the "Issues" tab on GitHub, or in our Discord server.

</details>

> If you just purchased a listed domain: The domain owner before you might have done some illegal activities with your domain. Please contact us so we can remove your domain from our lists. Also contact your domain registrar if needed, to _~~check,~~_ **check** if your domain is off their abuse lists _~~too.~~_ **as well.**

<details>
<summary>Complete string</summary>

> If you just purchased a listed domain: The domain owner before you might have done some illegal activities with your domain. Please contact us so we can remove your domain from our lists. Also contact your domain registrar if needed, to check if your domain is off their abuse lists as well.

</details>

> Contact us for a list of _~~To-Do's.~~_ **actions you have to take to comply with our rules.** After you _~~comply with the rules,~~_ **have done everything from that list,** we will _~~remove your site from the list.~~_ **unblacklist your website.**

<details>
<summary>Complete string</summary>

> Contact us for a list of actions you have to take to comply with our rules. After you have done everything from that list, we will unblacklist your website.

</details>

> Still _~~got Questions?~~_ **have questions?**
> Contact _~~our Team~~_ **us** and we'll answer you as quickly as we can!
> You can also join our Discord Server to talk with us!

<details>
<summary>Complete string</summary>

> Still have questions?
> Contact us and we'll answer you as quickly as we can!
> You can also join our Discord Server to talk with us!

</details>

## Downloads

> You can implement our Splash Screen _~~Mod~~_ into your _~~Mod~~_ **Minecraft mod** to show a StopModReposts _~~spash~~_ **splash** screen at the first game start.
_~~It~~_ **This** informs _~~your~~_ users to download mods on trusted sites.

<details>
<summary>Complete string</summary>

> You can implement our Splash Screen into your Minecraft mod to show a StopModReposts splash screen at the first game start.
This informs users to download mods on trusted sites.

</details>

## Footer

> Help _~~us,~~_ **us help you** by using _~~this~~_ **our** hashtag on social media.

<details>
<summary>Complete string</summary>

> Help us help you by using out hashtag on social media.

</details>

> _~~StopModReposts © 2018-2019~~_ **© StopModReposts 2018-2019**

<details>
<summary>Complete string</summary>

> © StopModReposts 2018-2019

</details>

**Comment by berrysauce** [comment]
**Note to me:** Don't close the issue after completion!

Edit: FAQ, Downloads, and Footer remaining

**Comment by Alexejhero** [comment]
You can close the issue once everything has been updated
