### ISSUE TITLE
An export feature with google-search-blacklist addon compatibility

### ISSUE THREAD

**Issue by KuronekoLen** [StopModReposts/StopModReposts.github.io#39]
**Is your feature request related to a problem? Please describe.**
If you use a blacklist addon like [uBlacklist](https://github.com/iorate/uBlacklist) (erases results from Google search before they even load, very useful) you have to manually add it to your configuration with its syntax. Though this can be done in excel and some copy/pasting not everyone has the knowhow or means to do this.

**Describe the solution you'd like**
An export of the blacklist that appends `*://*.` and `/*` to the respective ends of each entry would allow for immediate import into the addon. Other methods such as Regex could be considered too.

Here's how such an export would look, converted from the current master list on the website: https://pastebin.com/Fksyh9Px

uBlacklist also has a subscription feature that could probably be utilized by this repo

**Comment by berrysauce** [comment]
Can you find a format that would fit here? https://github.com/StopModReposts/Illegal-Mod-Sites/wiki/API-access-and-formats

**Comment by bilde2910** [comment]
Added the `/ublacklist` endpoint to api.stopmodreposts.org. See if this format works for you:

https://api.stopmodreposts.org/ublacklist

**Comment by KuronekoLen** [comment]
Good man. Thank you.
